### ISSUE TITLE
Check box

### ISSUE THREAD

**Issue by Slyteer** [d1adev/PwnVoltaire#4]
Il n'y a pas de check box quand je lance le programme

**Comment by balayette** [comment]
Screen? 
L'API d'où je récupère les corrections est cassée dans tous les cas, ça marche sûrement pas tant que je fais pas une mise à jour.

**Comment by Slyteer** [comment]
m'enfin ca  ne marche pas que sur ma machine
![image](https://user-images.githubusercontent.com/17968821/32845510-249545c8-ca25-11e7-9434-e709c80352e1.png)

**Comment by balayette** [comment]
C'est juste que ton écran a une trop petite résolution pour afficher la fenêtre en entier, elle scale pas automatiquement. 
Tu peux changer la taille de la fenêtre, la position des boutons, etc en modifiant Form1 dans la solution.
